services:
  - type: web
    name: ecommerce-php
    env: php
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: SUPABASE_URL
        value: https://phmnvvuohcsqyttsnevd.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBobW52dnVvaGNzcXl0dHNuZXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0MDQxOTQsImV4cCI6MjA3NTk4MDE5NH0._rJHUnp1wEm0D7tcLwUXfIltVLAyxp0rxkpvhEvBs-M
